name: Daily Auto Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "23f2000098@ds.study.iitm.ac.in"

      - name: Make Changes
        run: |
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt

      - name: Commit and Push Changes
        run: |
          git commit -m "Automated commit: $(date)"
          git push
